---
openapi: 3.0.0
info:
   version: 1.3.0
   title: weconnecttemplate open api specification
   description: connect API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8007
     description: connect
tags:
- name: connect
paths:
   "/connect":
      post:
         tags:
         -  connect
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/connect"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      connect:
         type: object
         properties:
            Name:
               type: "string"
               description: Description